automerge: false
files:
  maintainers: $team_nxos
  docs/:
    labels: docs
  $action/:
    labels: action
  $callback/:
    labels: callback
  $doc_fragments/:
    labels: doc_fragments
  $doc_fragments/nxos.py:
  $inventory/:
    labels: inventory
  $lookup/:
    labels: lookup
  $module_utils/:
    labels: module_utils
  $modules/:
    maintainers: $team_nxos
    labels: modules
  scripts/inventory/:
    labels: inventory
  tests/:
    labels: tests
  tests/integration/:
    labels: integrations
  tests/units/:
    labels: units
macros:
  action: plugins/action
  callback: plugins/callback
  doc_fragments: plugins/doc_fragments
  inventory: plugins/inventory
  lookup: plugins/lookup
  module_utils: plugins/module_utils
  modules: plugins/modules
  team_nxos: NilashishC
