authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=8.1.0"
license_file: LICENSE
name: nxos
namespace: cisco
description: Ansible Network Collection for Cisco NXOS devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.nxos
issues: https://github.com/ansible-collections/cisco.nxos/issues
tags: [cisco, nxos, networking, nxapi, netconf]
version: "11.0.0"
