---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.6.1"
license_file: LICENSE
name: nxos
namespace: cisco
description: Ansible Network Collection for Cisco NXOS devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.nxos
issues: https://github.com/ansible-collections/cisco.nxos/issues
tags: [cisco, nxos, networking, nxapi, netconf]
# NOTE(pabelanger): We create 0.0.0 version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: 4.3.1-dev
