authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=8.2.2"
license_file: LICENSE
name: nxos
namespace: cisco
description: Ansible Network Collection for Cisco NXOS devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.nxos
issues: https://github.com/ansible-collections/cisco.nxos/issues
tags: [cisco, nxos, networking, nxapi, netconf]
build_ignore:
  - .prettierignore
  - .pre-commit-config.yaml
  - .isort.cfg
  - .gitignore
  - .flake8
  - .ansible-lint
  - sonar-project.properties
  - codecov.yml
  - .github/
version: "11.1.1"
