[tool.black]
line-length = 79

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    'ignore:AnsibleCollectionFinder has already been configured',
    'ignore:_AnsibleCollectionFinder.find_spec().*',
]
