[tool.black]
line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
  'ignore:AnsibleCollectionFinder has already been configured',
  'ignore:_AnsibleCollectionFinder.find_spec().*',
]
