all:
  children:
    nxos_cisshgo:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.nxos.nxos
        ansible_user: admin
        ansible_password: admin
        ansible_host: 127.0.0.1
        ansible_command_timeout: 200
        ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        ansible_network_cli_ssh_type: libssh
        ansible_libssh_hostkeys: +ssh-rsa
        ansible_become: false
      children:
        nxos_ntp_global_gathered:
          hosts:
            cisshgo-ntp_global-gathered:
              ansible_port: 10001
        nxos_ntp_global_merged:
          hosts:
            cisshgo-ntp_global-merged:
              ansible_port: 10002
        nxos_ntp_global_replaced:
          hosts:
            cisshgo-ntp_global-replaced:
              ansible_port: 10003
        nxos_ntp_global_overridden:
          hosts:
            cisshgo-ntp_global-overridden:
              ansible_port: 10004
        nxos_ntp_global_deleted:
          hosts:
            cisshgo-ntp_global-deleted:
              ansible_port: 10005
