plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf:
    nxos:
      description: Use NX-OS cliconf to run commands on Cisco NX-OS platform
      name: nxos
      version_added: 1.0.0
  connection: {}
  httpapi:
    nxos:
      description: Use NX-API to run commands on Cisco NX-OS platform
      name: nxos
      version_added: 1.0.0
  inventory: {}
  lookup: {}
  module:
    nxos_aaa_server:
      description: Manages AAA server global configuration.
      name: nxos_aaa_server
      namespace: ''
      version_added: 1.0.0
    nxos_aaa_server_host:
      description: Manages AAA server host-specific configuration.
      name: nxos_aaa_server_host
      namespace: ''
      version_added: 1.0.0
    nxos_acl:
      description: (deprecated, removed after 2022-06-01) Manages access list entries
        for ACLs.
      name: nxos_acl
      namespace: ''
      version_added: 1.0.0
    nxos_acl_interface:
      description: (deprecated, removed after 2022-06-01) Manages applying ACLs to
        interfaces.
      name: nxos_acl_interface
      namespace: ''
      version_added: 1.0.0
    nxos_acl_interfaces:
      description: ACL interfaces resource module
      name: nxos_acl_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_acls:
      description: ACLs resource module
      name: nxos_acls
      namespace: ''
      version_added: 1.0.0
    nxos_banner:
      description: Manage multiline banners on Cisco NXOS devices
      name: nxos_banner
      namespace: ''
      version_added: 1.0.0
    nxos_bfd_global:
      description: Bidirectional Forwarding Detection (BFD) global-level configuration
      name: nxos_bfd_global
      namespace: ''
      version_added: 1.0.0
    nxos_bfd_interfaces:
      description: BFD interfaces resource module
      name: nxos_bfd_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_bgp:
      description: (deprecated, removed after 2023-01-27) Manages BGP configuration.
      name: nxos_bgp
      namespace: ''
      version_added: 1.0.0
    nxos_bgp_address_family:
      description: BGP Address Family resource module.
      name: nxos_bgp_address_family
      namespace: ''
      version_added: 2.0.0
    nxos_bgp_af:
      description: (deprecated, removed after 2023-02-24) Manages BGP Address-family
        configuration.
      name: nxos_bgp_af
      namespace: ''
      version_added: 1.0.0
    nxos_bgp_global:
      description: BGP Global resource module.
      name: nxos_bgp_global
      namespace: ''
      version_added: 1.4.0
    nxos_bgp_neighbor:
      description: (deprecated, removed after 2023-01-27) Manages BGP neighbors configurations.
      name: nxos_bgp_neighbor
      namespace: ''
      version_added: 1.0.0
    nxos_bgp_neighbor_address_family:
      description: BGP Neighbor Address Family resource module.
      name: nxos_bgp_neighbor_address_family
      namespace: ''
      version_added: 2.0.0
    nxos_bgp_neighbor_af:
      description: (deprecated, removed after 2023-02-24) Manages BGP address-family's
        neighbors configuration.
      name: nxos_bgp_neighbor_af
      namespace: ''
      version_added: 1.0.0
    nxos_command:
      description: Run arbitrary command on Cisco NXOS devices
      name: nxos_command
      namespace: ''
      version_added: 1.0.0
    nxos_config:
      description: Manage Cisco NXOS configuration sections
      name: nxos_config
      namespace: ''
      version_added: 1.0.0
    nxos_devicealias:
      description: Configuration of device alias for Cisco NXOS MDS Switches.
      name: nxos_devicealias
      namespace: storage
      version_added: 1.0.0
    nxos_evpn_global:
      description: Handles the EVPN control plane for VXLAN.
      name: nxos_evpn_global
      namespace: ''
      version_added: 1.0.0
    nxos_evpn_vni:
      description: Manages Cisco EVPN VXLAN Network Identifier (VNI).
      name: nxos_evpn_vni
      namespace: ''
      version_added: 1.0.0
    nxos_facts:
      description: Gets facts about NX-OS switches
      name: nxos_facts
      namespace: ''
      version_added: 1.0.0
    nxos_feature:
      description: Manage features in NX-OS switches.
      name: nxos_feature
      namespace: ''
      version_added: 1.0.0
    nxos_file_copy:
      description: Copy a file to a remote NXOS device.
      name: nxos_file_copy
      namespace: ''
      version_added: 1.0.0
    nxos_gir:
      description: Trigger a graceful removal or insertion (GIR) of the switch.
      name: nxos_gir
      namespace: ''
      version_added: 1.0.0
    nxos_gir_profile_management:
      description: Create a maintenance-mode or normal-mode profile for GIR.
      name: nxos_gir_profile_management
      namespace: ''
      version_added: 1.0.0
    nxos_hsrp:
      description: Manages HSRP configuration on NX-OS switches.
      name: nxos_hsrp
      namespace: ''
      version_added: 1.0.0
    nxos_hsrp_interfaces:
      description: HSRP interfaces resource module
      name: nxos_hsrp_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_igmp:
      description: Manages IGMP global configuration.
      name: nxos_igmp
      namespace: ''
      version_added: 1.0.0
    nxos_igmp_interface:
      description: Manages IGMP interface configuration.
      name: nxos_igmp_interface
      namespace: ''
      version_added: 1.0.0
    nxos_igmp_snooping:
      description: Manages IGMP snooping global configuration.
      name: nxos_igmp_snooping
      namespace: ''
      version_added: 1.0.0
    nxos_install_os:
      description: Set boot options like boot, kickstart image and issu.
      name: nxos_install_os
      namespace: ''
      version_added: 1.0.0
    nxos_interface:
      description: (deprecated, removed after 2022-06-01) Manages physical attributes
        of interfaces.
      name: nxos_interface
      namespace: ''
      version_added: 1.0.0
    nxos_interface_ospf:
      description: (deprecated, removed after 2022-10-26) Manages configuration of
        an OSPF interface instance.
      name: nxos_interface_ospf
      namespace: ''
      version_added: 1.0.0
    nxos_interfaces:
      description: Interfaces resource module
      name: nxos_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_l2_interface:
      description: (deprecated, removed after 2022-06-01) Manage Layer-2 interface
        on Cisco NXOS devices.
      name: nxos_l2_interface
      namespace: ''
      version_added: 1.0.0
    nxos_l2_interfaces:
      description: L2 interfaces resource module
      name: nxos_l2_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_l3_interface:
      description: (deprecated, removed after 2022-06-01) Manage L3 interfaces on
        Cisco NXOS network devices
      name: nxos_l3_interface
      namespace: ''
      version_added: 1.0.0
    nxos_l3_interfaces:
      description: L3 interfaces resource module
      name: nxos_l3_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_lacp:
      description: LACP resource module
      name: nxos_lacp
      namespace: ''
      version_added: 1.0.0
    nxos_lacp_interfaces:
      description: LACP interfaces resource module
      name: nxos_lacp_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_lag_interfaces:
      description: LAG interfaces resource module
      name: nxos_lag_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_linkagg:
      description: (deprecated, removed after 2022-06-01) Manage link aggregation
        groups on Cisco NXOS devices.
      name: nxos_linkagg
      namespace: ''
      version_added: 1.0.0
    nxos_lldp:
      description: (deprecated, removed after 2022-06-01) Manage LLDP configuration
        on Cisco NXOS network devices.
      name: nxos_lldp
      namespace: ''
      version_added: 1.0.0
    nxos_lldp_global:
      description: LLDP resource module
      name: nxos_lldp_global
      namespace: ''
      version_added: 1.0.0
    nxos_lldp_interfaces:
      description: LLDP interfaces resource module
      name: nxos_lldp_interfaces
      namespace: ''
      version_added: 1.0.0
    nxos_logging:
      description: Manage logging on network devices
      name: nxos_logging
      namespace: ''
      version_added: 1.0.0
    nxos_ntp:
      description: Manages core NTP configuration.
      name: nxos_ntp
      namespace: ''
      version_added: 1.0.0
    nxos_ntp_auth:
      description: Manages NTP authentication.
      name: nxos_ntp_auth
      namespace: ''
      version_added: 1.0.0
    nxos_ntp_options:
      description: Manages NTP options.
      name: nxos_ntp_options
      namespace: ''
      version_added: 1.0.0
    nxos_nxapi:
      description: Manage NXAPI configuration on an NXOS device.
      name: nxos_nxapi
      namespace: ''
      version_added: 1.0.0
    nxos_ospf:
      description: (deprecated, removed after 2022-06-01) Manages configuration of
        an ospf instance.
      name: nxos_ospf
      namespace: ''
      version_added: 1.0.0
    nxos_ospf_interfaces:
      description: OSPF Interfaces Resource Module.
      name: nxos_ospf_interfaces
      namespace: ''
      version_added: 1.3.0
    nxos_ospf_vrf:
      description: (deprecated, removed after 2022-10-01)Manages a VRF for an OSPF
        router.
      name: nxos_ospf_vrf
      namespace: ''
      version_added: 1.0.0
    nxos_ospfv2:
      description: OSPFv2 resource module
      name: nxos_ospfv2
      namespace: ''
      version_added: 1.0.0
    nxos_ospfv3:
      description: OSPFv3 resource module
      name: nxos_ospfv3
      namespace: ''
      version_added: 1.2.0
    nxos_overlay_global:
      description: Configures anycast gateway MAC of the switch.
      name: nxos_overlay_global
      namespace: ''
      version_added: 1.0.0
    nxos_pim:
      description: Manages configuration of a PIM instance.
      name: nxos_pim
      namespace: ''
      version_added: 1.0.0
    nxos_pim_interface:
      description: Manages PIM interface configuration.
      name: nxos_pim_interface
      namespace: ''
      version_added: 1.0.0
    nxos_pim_rp_address:
      description: Manages configuration of an PIM static RP address instance.
      name: nxos_pim_rp_address
      namespace: ''
      version_added: 1.0.0
    nxos_ping:
      description: Tests reachability using ping from Nexus switch.
      name: nxos_ping
      namespace: ''
      version_added: 1.0.0
    nxos_reboot:
      description: Reboot a network device.
      name: nxos_reboot
      namespace: ''
      version_added: 1.0.0
    nxos_rollback:
      description: Set a checkpoint or rollback to a checkpoint.
      name: nxos_rollback
      namespace: ''
      version_added: 1.0.0
    nxos_rpm:
      description: Install patch or feature rpms on Cisco NX-OS devices.
      name: nxos_rpm
      namespace: ''
      version_added: 1.0.0
    nxos_smu:
      description: (deprecated, removed after 2022-10-01) Perform SMUs on Cisco NX-OS
        devices.
      name: nxos_smu
      namespace: ''
      version_added: 1.0.0
    nxos_snapshot:
      description: Manage snapshots of the running states of selected features.
      name: nxos_snapshot
      namespace: ''
      version_added: 1.0.0
    nxos_snmp_community:
      description: Manages SNMP community configs.
      name: nxos_snmp_community
      namespace: ''
      version_added: 1.0.0
    nxos_snmp_contact:
      description: Manages SNMP contact info.
      name: nxos_snmp_contact
      namespace: ''
      version_added: 1.0.0
    nxos_snmp_host:
      description: Manages SNMP host configuration.
      name: nxos_snmp_host
      namespace: ''
      version_added: 1.0.0
    nxos_snmp_location:
      description: Manages SNMP location information.
      name: nxos_snmp_location
      namespace: ''
      version_added: 1.0.0
    nxos_snmp_traps:
      description: Manages SNMP traps.
      name: nxos_snmp_traps
      namespace: ''
      version_added: 1.0.0
    nxos_snmp_user:
      description: Manages SNMP users for monitoring.
      name: nxos_snmp_user
      namespace: ''
      version_added: 1.0.0
    nxos_static_route:
      description: (deprecated, removed after 2022-06-01) Manages static route configuration
      name: nxos_static_route
      namespace: ''
      version_added: 1.0.0
    nxos_static_routes:
      description: Static routes resource module
      name: nxos_static_routes
      namespace: ''
      version_added: 1.0.0
    nxos_system:
      description: Manage the system attributes on Cisco NXOS devices
      name: nxos_system
      namespace: ''
      version_added: 1.0.0
    nxos_telemetry:
      description: TELEMETRY resource module
      name: nxos_telemetry
      namespace: ''
      version_added: 1.0.0
    nxos_udld:
      description: Manages UDLD global configuration params.
      name: nxos_udld
      namespace: ''
      version_added: 1.0.0
    nxos_udld_interface:
      description: Manages UDLD interface configuration params.
      name: nxos_udld_interface
      namespace: ''
      version_added: 1.0.0
    nxos_user:
      description: Manage the collection of local users on Nexus devices
      name: nxos_user
      namespace: ''
      version_added: 1.0.0
    nxos_vlan:
      description: (deprecated, removed after 2022-06-01) Manages VLAN resources and
        attributes.
      name: nxos_vlan
      namespace: ''
      version_added: 1.0.0
    nxos_vlans:
      description: VLANs resource module
      name: nxos_vlans
      namespace: ''
      version_added: 1.0.0
    nxos_vpc:
      description: Manages global VPC configuration
      name: nxos_vpc
      namespace: ''
      version_added: 1.0.0
    nxos_vpc_interface:
      description: Manages interface VPC configuration
      name: nxos_vpc_interface
      namespace: ''
      version_added: 1.0.0
    nxos_vrf:
      description: Manages global VRF configuration.
      name: nxos_vrf
      namespace: ''
      version_added: 1.0.0
    nxos_vrf_af:
      description: Manages VRF AF.
      name: nxos_vrf_af
      namespace: ''
      version_added: 1.0.0
    nxos_vrf_interface:
      description: Manages interface specific VRF configuration.
      name: nxos_vrf_interface
      namespace: ''
      version_added: 1.0.0
    nxos_vrrp:
      description: Manages VRRP configuration on NX-OS switches.
      name: nxos_vrrp
      namespace: ''
      version_added: 1.0.0
    nxos_vsan:
      description: Configuration of vsan for Cisco NXOS MDS Switches.
      name: nxos_vsan
      namespace: storage
      version_added: 1.0.0
    nxos_vtp_domain:
      description: Manages VTP domain configuration.
      name: nxos_vtp_domain
      namespace: ''
      version_added: 1.0.0
    nxos_vtp_password:
      description: Manages VTP password configuration.
      name: nxos_vtp_password
      namespace: ''
      version_added: 1.0.0
    nxos_vtp_version:
      description: Manages VTP version configuration.
      name: nxos_vtp_version
      namespace: ''
      version_added: 1.0.0
    nxos_vxlan_vtep:
      description: Manages VXLAN Network Virtualization Endpoint (NVE).
      name: nxos_vxlan_vtep
      namespace: ''
      version_added: 1.0.0
    nxos_vxlan_vtep_vni:
      description: Creates a Virtual Network Identifier member (VNI)
      name: nxos_vxlan_vtep_vni
      namespace: ''
      version_added: 1.0.0
    nxos_zone_zoneset:
      description: Configuration of zone/zoneset for Cisco NXOS MDS Switches.
      name: nxos_zone_zoneset
      namespace: storage
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 2.0.0
