devices:
  - platform: nxos_lldp_interfaces
    count: 1
  - scenario: nxos-lldp-interfaces-gathered
    count: 1
  - scenario: nxos-lldp-interfaces-merged
    count: 1
  - scenario: nxos-lldp-interfaces-replaced
    count: 1
  - scenario: nxos-lldp-interfaces-overridden
    count: 1
  - scenario: nxos-lldp-interfaces-deleted
    count: 1
