devices:
  - scenario: nxos-prefix-lists-gathered
    count: 1
  - scenario: nxos-prefix-lists-gathered
    count: 1
  - scenario: nxos-prefix-lists-merged
    count: 1
  - scenario: nxos-prefix-lists-replaced
    count: 1
  - scenario: nxos-prefix-lists-overridden
    count: 1
  - scenario: nxos-prefix-lists-deleted
    count: 1
