---
name: Bug Report
description: "🐞 Create a report to help us improve"
body:
  - type: markdown
    attributes:
      value: |
        Bug Report issues are for **concrete, actionable bugs** only.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the problem.
    validations:
      required: false

  - type: checkboxes
    id: components
    attributes:
      label: Select the relevant components
      options:
        - label: Module
        - label: Action Plugin
        - label: Connection Plugin (cliconf)
        - label: HTTP API Plugin
        - label: Terminal Plugin
        - label: Netconf Plugin
        - label: Module Utils
        - label: Documentation
        - label: Integration Tests
        - label: Unit Tests
        - label: Collection Release
        - label: CI Maintenance
        - label: Workflow Maintenance

  - type: input
    id: nxos_version
    attributes:
      label: NX-OS Version
      description: Version of NX-OS running on the device (e.g., 7.0(3)I7, 9.3(3), 10.2(1))
      placeholder: 7.x / 9.x / 10.x
    validations:
      required: false

  - type: input
    id: hardware_platform
    attributes:
      label: Hardware Platform
      description: Hardware platform if applicable (e.g., Nexus 9000, Nexus 7000, Nexus 3000, N9Kv)
      placeholder: Nexus 9000 / Nexus 7000 / Nexus 3000 / N9Kv
    validations:
      required: false

  - type: input
    id: module_name
    attributes:
      label: Module/Plugin Name
      description: If applicable, specify the module or plugin name (e.g., nxos_config, nxos_bgp_global)
      placeholder: nxos_xxx
    validations:
      required: false
