driver:
  name: default
platforms:
  - name: cisshgo-ntp_global-gathered
  - name: cisshgo-ntp_global-merged
  - name: cisshgo-ntp_global-replaced
  - name: cisshgo-ntp_global-overridden
  - name: cisshgo-ntp_global-deleted
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../cisshgo_fixtures/inventories/ansible/ntp_global.yaml
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_HOST_KEY_CHECKING: "false"
    ANSIBLE_DEPRECATION_WARNINGS: "false"
  config_options:
    defaults:
      inventory: ${MOLECULE_SCENARIO_DIRECTORY}/../cisshgo_fixtures/inventories/ansible/ntp_global.yaml
  playbooks:
    create: ../_shared/create.yml
    converge: converge.yml
    verify: ../_shared/verify.yml
    destroy: ../_shared/destroy.yml
scenario:
  test_sequence:
    - create
    - converge
    - verify
    - destroy
prerun: false
verifier:
  name: ansible
