name: run-cov

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  #codecoverage
  codecov:
    uses: ./.github/workflows/covflow.yml
    with:
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
