name: Units (dependencies from galaxy)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  unit:
    uses: ansible-network/github_actions/.github/workflows/unit_simple.yml@main
    with:
      collection_dependencies: >-
        ansible.netcommon>=2.6.1
